services:
  app:
    build: .
    container_name: app-container
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:17.2
    container_name: db-container
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=hakaton
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

