services:
  web:
    build: .
    container_name: sport-events-main
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
      - IS_PROD=1
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      # - ./app:/app/app  # Закомментировал, чтобы использовать собранную версию
      - ./bot:/app/bot  # Для логов бота
      - ./parsing:/app/parsing  # Для логов парсинга

  db:
    image: postgres:17.2
    container_name: sport-events-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=hakaton
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

