from enum import Enum

class Regions(Enum):
    # 22 Республики
    ADYGEA = "Республика Адыгея"
    ALTAI_REPUBLIC = "Республика Алтай"
    BASHKORTOSTAN = "Республика Башкортостан"
    BURYATIA = "Республика Бурятия"
    DAGESTAN = "Республика Дагестан"
    DONECK = "Донецкая Народная Республика"
    INGUSHETIA = "Республика Ингушетия"
    KABARDINO_BALKARIA = "Кабардино-Балкарская Республика"
    KALMYKIA = "Республика Калмыкия"
    KARACHAY_CHERKESSIA = "Карачаево-Черкесская Республика"
    KARELIA = "Республика Карелия"
    KOMI = "Республика Коми"
    CRIMEA = "Республика Крым"
    MARI_EL = "Республика Марий Эл"
    MORDOVIA = "Республика Мордовия"
    SAKHA_YAKUTIA = "Республика Саха-Якутия"
    NORTH_OSSETIA_ALANIA = "Республика Северная Осетия - Алания"
    TATARSTAN = "Республика Татарстан"
    TUVA = "Республика Тыва"
    UDMURTIA = "Удмуртская Республика"
    KHAKASSIA = "Республика Хакасия"
    CHECHNYA = "Чеченская Республика"
    CHUVASHIA = "Чувашская Республика"
    LUGANSK = "Луганская Народная Республика"

    # 9 Краёв
    ALTAY_TERRITORY = "Алтайский край"
    ZABAIKALSKY_TERRITORY = "Забайкальский край"
    KAMCHATKA_TERRITORY = "Камчатский край"
    KRASNODAR_TERRITORY = "Краснодарский край"
    KRASNOYARSK_TERRITORY = "Красноярский край"
    PERM_TERRITORY = "Пермский край"
    PRIMORSKY_TERRITORY = "Приморский край"
    STAVROPOL_TERRITORY = "Ставропольский край"
    KHABAROVSK_TERRITORY = "Хабаровский край"

    # 46 Областей
    AMUR_REGION = "Амурская область"
    ARKHANGELSK_REGION = "Архангельская область"
    ASTRAKHAN_REGION = "Астраханская область"
    BELGOROD_REGION = "Белгородская область"
    BRYANSK_REGION = "Брянская область"
    VLADIMIR_REGION = "Владимирская область"
    VOLGOGRAD_REGION = "Волгоградская область"
    VOLOGDA_REGION = "Вологодская область"
    VORONEZH_REGION = "Воронежская область"
    IVANOVO_REGION = "Ивановская область"
    IRKUTSK_REGION = "Иркутская область"
    KALININGRAD_REGION = "Калининградская область"
    KALUGA_REGION = "Калужская область"
    KEMEROVO_REGION = "Кемеровская область - Кузбасс"
    KIROV_REGION = "Кировская область"
    KOSTROMA_REGION = "Костромская область"
    KURGAN_REGION = "Курганская область"
    KURSK_REGION = "Курская область"
    LENINGRAD_REGION = "Ленинградская область"
    LIPETSK_REGION = "Липецкая область"
    MAGADAN_REGION = "Магаданская область"
    MOSCOW_REGION = "Московская область"
    MURMANSK_REGION = "Мурманская область"
    NIZHNY_NOVGOROD_REGION = "Нижегородская область"
    NOVGOROD_REGION = "Новгородская область"
    NOVOSIBIRSK_REGION = "Новосибирская область"
    OMSK_REGION = "Омская область"
    ORENBURG_REGION = "Оренбургская область"
    ORYOL_REGION = "Орловская область"
    PENZA_REGION = "Пензенская область"
    PSKOV_REGION = "Псковская область"
    ROSTOV_REGION = "Ростовская область"
    RYAZAN_REGION = "Рязанская область"
    SAMARA_REGION = "Самарская область"
    SARATOV_REGION = "Саратовская область"
    SAKHALIN_REGION = "Сахалинская область"
    SVERDLOVSK_REGION = "Свердловская область"
    SMOLENSK_REGION = "Смоленская область"
    TAMBOV_REGION = "Тамбовская область"
    TVER_REGION = "Тверская область"
    TOMSK_REGION = "Томская область"
    TULA_REGION = "Тульская область"
    TYUMEN_REGION = "Тюменская область"
    ULYANOVSK_REGION = "Ульяновская область"
    CHELYABINSK_REGION = "Челябинская область"
    YAROSLAVL_REGION = "Ярославская область"
    ZAPOROZHIE = "Запорожская область"
    HERSONSK = "Херсонская область"

    # 3 Города федерального значения
    MOSCOW = "г. Москва"
    SAINT_PETERSBURG = "г. Санкт Петербург"
    SEVASTOPOL = "город Севастополь"

    # 1 Автономная область
    JEWISH_AUTONOMOUS_REGION = "Еврейский АО"

    # 4 Автономных округа
    NENETS_AUTONOMOUS_OKRUG = "Ненецкий автономный округ"
    KHANTY_MANSI_AUTONOMOUS_OKRUG = "Ханты-Мансийский автономный округ – Югра"
    CHUKOTKA_AUTONOMOUS_OKRUG = "Чукотский АО"
    YAMAL_NENETS_AUTONOMOUS_OKRUG = "Ямало-Ненецкий АО"

if __name__ == "__main__":
    print(len(list(Regions)))
