site_url: https://minsport.gov.ru/activity/government-regulation/edinyj-kalendarnyj-plan/
pdf_pattern: /cms-uploads/cms/II_chast_EKP[^"']+\.pdf
record_number_pattern: ([А-Я\s\(\)-]+)\nОсновной состав

