"""Add change id defaultfor FSP archives

Revision ID: e67b22fee3f5
Revises: 32b757294d7c
Create Date: 2024-12-06 18:32:28.155783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e67b22fee3f5"
down_revision: Union[str, None] = "32b757294d7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "fsp_events_archive", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "fsp_events_archive", type_="unique")
    # ### end Alembic commands ###
