"""Add gender field to events

Revision ID: 18eb5c09a2f4
Revises: 306bd5fbb046
Create Date: 2024-11-23 00:18:10.917113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "18eb5c09a2f4"
down_revision: Union[str, None] = "306bd5fbb046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("gender", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    op.create_unique_constraint(None, "events", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, "events", type_="unique")
    op.drop_column("events", "gender")
    # ### end Alembic commands ###
