"""Add fsp_events_archive table

Revision ID: 32b757294d7c
Revises: 0bf2734331f0
Create Date: 2024-12-06 18:11:46.599427

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "32b757294d7c"
down_revision: Union[str, None] = "0bf2734331f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fsp_events_archive",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sport", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("participants", sa.String(), nullable=True),
        sa.Column("participants_num", sa.String(), nullable=True),
        sa.Column("discipline", sa.String(), nullable=True),
        sa.Column(
            "region",
            sa.dialects.postgresql.ENUM(
                name="regions",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("representative", sa.String(), nullable=True),
        sa.Column("place", sa.String(), nullable=True),
        sa.Column("date_start", sa.DateTime(), nullable=False),
        sa.Column("date_end", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.dialects.postgresql.ENUM(
                name="fspeventstatus",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("files", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fsp_events_archive")
    # ### end Alembic commands ###
