"""Add sport field to events table

Revision ID: ba749fd5b080
Revises: 18eb5c09a2f4
Create Date: 2024-11-23 00:47:38.703316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba749fd5b080"
down_revision: Union[str, None] = "18eb5c09a2f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("sport", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "sport")
    # ### end Alembic commands ###
